services:
  rxtrax-frontend:
    container_name: rxtrax-frontend
    image: git.postfmly.com/admin/rxtrax-frontend:arm64
    restart: unless-stopped
    depends_on:
      - rxtrax-backend
    ports:
      - "90:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=RxTrax (Frontend)
      - homepage.group=Personal
      - homepage.name=RxTrax
      - homepage.icon=https://rx.postfmly.com/rxtrax.png
      - homepage.href=https://rx.postfmly.com/
      - homepage.description=rx.postfmly.com

  rxtrax-backend:
    container_name: rxtrax-backend
    image: git.postfmly.com/admin/rxtrax-backend:arm64
    restart: unless-stopped
    ports:
      - "5556:5556"
    volumes:
      - db:/backend/db
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=RxTrax (Backend)
    stop_signal: SIGINT

volumes:
  db:

networks: {}

x-dockge:
  urls:
    - https://rx.postfmly.com
